### ISSUE TITLE
T-Clock not working

### ISSUE THREAD

**Issue by l0oo** [dremin/RetroBar#110]
Hello!
Thank you very much for an awesome piece of software! Well done! :) Could you add possibility to use T-Clock as clock? :)
BTW: Are possible inverted colours of white icons in tray?

Rgrds

**Comment by l0oo** [comment]
Hello 
Thanks for answer! :)

 _I don't think it's impossible._

Well - it is ;) and was - dunno how it is made... But I use it on W7 taskbar, also W10 taskbar can do that, even at early W11 taskbar it was possible to do. So there must be the way, :) T-Clock is the great add-on to the classic Windows interface.

As for tray icons, well - would be just great to have them black, I am old-fashioned and prefer Light Win mode. :)

**Comment by xoascf** [comment]
@l0oo, I don't really know why, but you're right, it looks like a regression that makes the taskbar less functional or customizable.
If you mean the TrayClockWClass (OS dependent but from old taskbar), probably, sure it is possible.
Heyy...@dremin is the actual developer, not me XD, I just implemented (for now) the localization engine based on the theme one.

I'm not really sure, check the [repository](https://github.com/White-Tiger/T-Clock), it seems to be abandoned since 2018.
I know, it's a nice application, and yes, I think part of those features are in the roadmap, as actually most of them are from versions somewhat earlier than Windows 7, and if not, they would be part of a QoL update since they are important to customize and let the user choose what appears and what doesn't.

It looks clean and classic, simple but not too much, just as a good UI should be.
You can remove it with a tool called [7+ Taskbar Tweaker](https://rammichael.com/7-taskbar-tweaker).

**Comment by dremin** [comment]
I can foresee several complications supporting T-Clock, especially while Explorer is still running with its own taskbar. As an alternative, I could add custom date/time formatting options for the taskbar clock which would allow you to replicate what's in the screenshot.

**Comment by dremin** [comment]
Supporting T-Clock is not planned, but there will be a feature allowing themes to replicate T-Clock appearance and date/time format in the next release.
