### ISSUE TITLE
Confusion about Taskbar Texture

### ISSUE THREAD

**Issue by SoniKast** [dremin/RetroBar#231]
Hello, I'm trying to make a royale theme for RetroBar, but I'm facing an issue where... 
Well, I don't really understand how the taskbar texture works. I looked at the original taskbar code, but it just doesn't make sense to me. Can anyone explain to me how it works please?

Thanks!

**Comment by AveYo** [comment]
xaml sucks. But you can do nice stuff with gradients & etc.  
Can take my [ShittyDark](https://github.com/dremin/RetroBar/issues/206) modification of XP Blue as reference - I've used gradients for most states (hover, active..)

**Comment by ColdSalt09** [comment]
royale theme is already created by @dremin

**Comment by dremin** [comment]
Closing due to Royale theme being complete already for the next release.

For reference, the taskbar background for the XP themes is using a XAML gradient, which you can learn more about [on this page](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/graphics-multimedia/painting-with-solid-colors-and-gradients-overview?view=netframeworkdesktop-4.8).
