### ISSUE TITLE
[suggestion] Retrobar + add Shell Enhancement for wine ( if [Retrobar => Wine] start shellenhamcement plugins and runtimemanager and Bar at right side)

### ISSUE THREAD

**Issue by blackcrack** [dremin/RetroBar#339]
Hi,

why supports Retrobar not via plugin-dll in Linux a Shell replacement for have a surface and a startpaneel for Wine in a Linux-Desktop ?

by start checks retrobar if have a wine-environment and which version of emulated WinNt is running, then use the right theme and place the Retrobar at first on the "Right" (not left side) side and make it able for start/add OpenShell as Startmenu.. this could be cool for the whole Linuxcommunity who use wine as WinNT environment and therewith could be Retrobar the head of the Wine-environment :) So, not only developing for MS-WinNt, nope, Useable also in a Wine-environment + plugins for more makea real WinNT(Windows-environment) for have better running Windows-programms aaand have a Startmenu for Wine in a Linux Windowmanager environment, like Plasma(Kde) and Gnome, i use plasma.. and then use the Retrobar as enhancement in Wine at the desktop :), first Start at the right side and later configurable like the user whant,on top, left or, if works bottom..

If this works, could be Retrobar also as a Windowmanager with wine-subsystem as a run allone behind the KDM/Sddm or Gdm

this would be a <strike>great</strike> huge thing imho, if this be able and possible..
need just easy "wine /path/to/retrobar.exe" in a script for run wine in Linux with Retrobar as Surface and starter of diffrent programms.. so, could be really cool.. and usable for the huge wine-community.. in Linux too....

and i bet, if Retrobar supports wine with runtime plugins, gives imho manny more peoples who works in Linux and deliver paches for Retrobar !

best regards
Blacky

**Comment by SlitEye** [comment]
Wine-Support isn't necessary, because RetroBar is based on .NET 6 (formerly .NET Core), which is platform independent (avaiable for Windows-, Linux- and macOS-Systems). 

If you need Wine-Support of RetroBar, please request this to the Wine-Developers. 

I think, that RetroBar shouldn't be the "Head of Wine Desktop Runtime". RetroBar should be a portable DeskBar (like PortableApps.com-DeskBar). But the idea, to use RetroBar as plattform independent DeskBar with the same Design/Theme, Launchers and Config on each Windows- and Linux [and maybe also for macOS] is really nice.

@Developers:
I don't know what .NET 6-API's you're using for the RetroBar-Implementation, but would it be realistic for you to imagine that you could make your RetroBar implementation platform independent with .NET 6?

**Comment by blackcrack** [comment]
and how want you let it run in Linux with WinNT binarys.. pfhh..
and ,.. - is a Net a commando interpreter ?

make an account and use it as trollaccount.. pffhh.. any year one activity..

**Comment by SlitEye** [comment]
> and how want you let it run in Linux without WinNT binary Interpreter..? pfhh..
> 
> and ,.. - is a Net a commando interpreter ?
> 
> 
> 
> Slitheye make an account and use it as trollaccount.. any year one activity.. 

What do you mean?

.NET (also available for Linux: .NET 6 (formerly .NET Core) as well as Mono) and PowerShell (also for Linux) already provide a runtime with interpreters for .NET-based languages/programs.

One should only not use platform-specific modules / APIs or use a multi-GUI backend. Alternatively, a cross-platform GUI binding for .NET would also work.

All this would be better than Wine.
Alternatively, Wine could support RetroBar, but not vice versa.

Also, RetroBar is not a window manager / desktop runtime, not a start menu, just a taskbar. A start menu could still be added in my opinion. However, a window management / desktop environment with window themes is utopian for RetroBar.

**Comment by blackcrack** [comment]
make you own tread..
