### ISSUE TITLE
Use dark system tray icons

### ISSUE THREAD

**Issue by Ryan659** [dremin/RetroBar#41]
With Windows 10 v1903 there came a new light theme that included dark system tray icons. If the RetroBar theme is set to a light one though (e.g. Win95, etc) those icons are too light to see since they still use the white icons, even if the system taskbar is light and uses the dark icons. Is it possible to use those dark icons there instead?

**Comment by ThePillenwerfer** [comment]
Agreed.  I tried this partly in the hope that they'd show up better than on the default W10 notification area.

**Comment by dremin** [comment]
This is now available in 1.8.

**Comment by Davoleo** [comment]
This is still broken for System & System XP themes, set to false here: https://github.com/dremin/RetroBar/commit/938624457d6375c82a9ac0bf0e5f9400669514f4#diff-1e83be7c081c5b2407d09eef45a437f8298ff19f1e2cb859a21765851c568765R44
I don't know if that's intended but it produces this result on Windows 10
![image](https://user-images.githubusercontent.com/24458276/161538293-1fa06881-5bd6-4d10-8ac0-8eccdb7fd223.png)

**Comment by xoascf** [comment]
@Davoleo, that's intentional, since we don't know what color scheme your system has, or if you have customized it, we can't choose for you the color of the icons. But I suppose you could automate it (depending on the tray or background color) behind the code instead of specifying it in the themes, but the user would no longer have a choice of dark or light color.
In any case there should be at least three selectable options: dark, light, defined by theme(?

**Comment by Davoleo** [comment]
mh then this is kinda odd, when I change my operating system theme, the bar just stays light, no matter what the choice in settings is, is this related to an existing bug or should I create an issue about it?

**Comment by dremin** [comment]
Unfortunately the color schemes exposed by the modern settings don't change the actual classic theme colors, however an application like this should: https://www.wintools.info/index.php/classic-color-panel

**Comment by markyb86** [comment]
> This is now available in 1.8.

I see the files added for this to work, but how does one go about using them?
