### ISSUE TITLE
windows 7 taskbars please?

### ISSUE THREAD

**Issue by IncompetentMoron** [dremin/RetroBar#478]
please
a lot of us are wondering why theyre not added in yet, but please add them in very much appreciated

**Comment by IncompetentMoron** [comment]
the style is just pure perfection

**Comment by 111ebobo** [comment]
> the style is just pure perfection

For me vista one is better and windows 7 one is not retro

**Comment by M1ghty-boy** [comment]
the main thing I miss using retrobar is task grouping/no titles, just icons. windows 7 taskbar would be perfect for me for that reason

**Comment by JohnCartoonist** [comment]
Windows 7 has a special nostalgic value to me; it is THE Windows of my childhood. I used to play so many Mario Flash games on it, it was the operating system that introduced me to emulation, its graphical user interface with the glossy taskbar, the glowing start button in the taskbar with that smooth transition has always looked magical to me and hearing that distinctive startup sound always brings me back to a simpler time!

I think you can already tell that I absolutely love Windows 7 and I really do! I wish to recapture that in RetroBar because of the operating system's significance on me.

**Comment by emeraldongithub** [comment]
> > the style is just pure perfection
> 
> For me vista one is better and windows 7 one is not retro

i consider anything before metro to be retro

**Comment by M1ghty-boy** [comment]
I mean imo anything that’s EOL/>10 years old should technically be considered retro but some may disagreeOn Dec 7, 2022, at 14:36, emeraldyy ***@***.***> wrote:﻿


the style is just pure perfection

For me vista one is better and windows 7 one is not retro

i consider anything before metro to be retro

**Comment by y2k04** [comment]
> > > the style is just pure perfection
> > 
> > 
> > For me vista one is better and windows 7 one is not retro
> 
> i consider anything before metro to be retro

same
