### ISSUE TITLE
Gap between taskbar and window when maximizing.

### ISSUE THREAD

**Issue by Kaloyan501** [dremin/RetroBar#518]
There is a gap between the window and the taskbar when I maximize a window.
OS: Windows 11 Insider Build 22623.1250
![Screenshot 2023-02-04 153504](https://user-images.githubusercontent.com/68351222/216770626-3ceeb2f8-f187-4d9e-acc3-890dbabf3f30.png)

**Comment by 111ebobo** [comment]
Try to turn on auto hide the taskbar, if it didn't work decrease it's size

**Comment by dremin** [comment]
I've started noticing this on the release version of Windows 11 with the latest updates. Looking into it.

**Comment by dremin** [comment]
Testing outside of RetroBar, it seems that sometimes when sending an `ABM_SETSTATE` message to the taskbar to enable auto-hide, it will revert the setting immediately. Since setting via the Settings app does not cause this, I'm guessing it is using a different method that we may be able to use instead. For now, enabling auto-hide via Settings before opening RetroBar is the best workaround.

**Comment by dremin** [comment]
Closing as issue is fixed by the above comment.
