### ISSUE TITLE
Inconsistent behavior with taskbar icons on Windows 11.

### ISSUE THREAD

**Issue by ScottVordem** [dremin/RetroBar#730]
I noticed some inconsistencies with the icons and notifications.

I'm using the "Windows XP Blue" theme.

For notifications regarding the icons in the taskbar, sometimes they show up in the classic balloon style like in XP while others still pop up in the modern Windows notification. It does not seem random as I noticed it is only with specific programs. More modern software use the modern notification while older software and Windows legacy components use the balloon style. I'm not sure if that is intended behavior, or those programs are sending the notification slightly differently.

I also noticed that not all the programs are showing up in RetroBar. I use [DS4Windows](https://github.com/Ryochan7/DS4Windows) and very quickly noticed that it's icon is not showing up in RetroBar, but shows on Windows 11's regular taskbar. Not sure why that is. I have DS4Windows setup to minimize to system tray. Does RetroBar not support the system tray?

**Comment by xoascf** [comment]
There are at least three reasons why applications may use a different balloon style and cause these inconsistencies:

- Modern "toast" notifications (UWP applications mostly use this style): They have a different way of handling them, since they are not exactly message balloons, it may be necessary to implement data redirection.
- Custom balloon control (some custom controls within WPF applications may also use this): We will not be able to do this unless there is some kind of data redirection from the control, but since there are many differences between implementations, this is probably impossible or really hard to do.
- Classic balloon style (if enabled in the registry) or modern "toast" notification (converted old balloons): Most of the time this is because the application did not set the window handle correctly (possibly just passed `null`) to `NOTIFYICONDATA`.

**Comment by dremin** [comment]
> I also noticed that not all the programs are showing up in RetroBar. I use [DS4Windows](https://github.com/Ryochan7/DS4Windows) and very quickly noticed that it's icon is not showing up in RetroBar, but shows on Windows 11's regular taskbar. Not sure why that is. I have DS4Windows setup to minimize to system tray. Does RetroBar not support the system tray?

Thanks for reporting this issue! It should work; I am preparing a fix.

**Comment by dremin** [comment]
Could you please report back if [this updated version](https://github.com/dremin/RetroBar/actions/runs/7255612225/artifacts/1122845189) works better with DS4Windows for you?

**Comment by ScottVordem** [comment]
Yep! It is showing up now. Thank you!
![image](https://github.com/dremin/RetroBar/assets/107659193/eaf11825-83d6-4dd1-a998-92568dd57771)
