### ISSUE TITLE
RetroBar 3.1.0 installer is to picky about .NET Core version

### ISSUE THREAD

**Issue by ToddAndMargo** [dremin/RetroBar#89]
![Screenshot_2021-09-12_17-34-39](https://user-images.githubusercontent.com/843205/133008654-5dfb6e1c-d8f5-4d02-b95b-b9dd9e43daef.png)

**Comment by xoascf** [comment]
Of course, that's because you have installed the wrong version, you need to download and install [.NET Desktop Runtime 3.1.18 instead of just .NET Runtime 3.1.18](https://dotnet.microsoft.com/download/dotnet/3.1).

It would probably be better if the [download link](https://dotnet.microsoft.com/download/dotnet/3.1/runtime) and download instructions (select "Run desktop apps" and below the system architecture on the page) were included in the README.md or the single binary automatically downloads the runtime.

**Comment by ToddAndMargo** [comment]
The installer opens to :+1:  https://dotnet.microsoft.com/download/dotnet/3.1/runtime?utm_source=getdotnetcore&utm_medium=referral

Desktop is not one of the download options

![Screenshot_2021-09-12_19-13-10](https://user-images.githubusercontent.com/843205/133014043-dcbcada1-54b3-4cef-a71c-5fa321b491d7.png)

**Comment by samiscoolest** [comment]
its run desktop apps

**Comment by ToddAndMargo** [comment]
On 9/12/21 10:03 PM, samiscoolest wrote:
> its run desktop apps

Makes sense.  Unfortunately, the installer sends you
to the wrong page.

**Comment by dremin** [comment]
I'll clarify this in the readme and release notes.
