### ISSUE TITLE
[FEATURE REQUEST and one little issue] tray icons, windows vista start button, calendar & time dialog

### ISSUE THREAD

**Issue by Mustardnote3943** [dremin/RetroBar#896]
moving system tray icons/notification icons would be nice so I can put a custom network tray icon between battery and sound. ![image](https://github.com/user-attachments/assets/8860329e-d9e3-4107-85de-ad8b7c59a08d)
the time button should open the calendar and clock dialog 
![image](https://github.com/user-attachments/assets/a7954b7c-3498-4261-87ec-8789c99294e2)
the windows vista start button should be in front of the start menu as this is how it should be shown. I use open shell as my start menu.
![Capture](https://github.com/user-attachments/assets/0067f88f-10b2-45e7-a114-557007e8af1c)

**Comment by GaryM99** [comment]
I won't address your latter 2 requests, since that involves recoding, but I can describe the workaround I used to get the tray icons in a preferred order.  It involves manual editing of RetroBar's configuration file instead, located here...
"C:\Users\<user name>\AppData\Local\RetroBar\settings.json".

First make a copy of the original file.  One of my attempts apparently had a mistake that caused RetroBar to revert to defaults, so keep your backup until you've got it working.  Using any text editor, go to the section labeled "NotifyIconBehaviors".  The icon entries are listed in the same order as they appear in the tray, and some entries have program paths while others have GUIDs that may make them hard to identify (except by their position).  Relocating your network icon should be a breeze.  I have nine "always show" icons and a specific order I wanted, so it was a bigger deal to me.

**Comment by Mustardnote3943** [comment]
and how do I exactly do that on the json file?

**Comment by GaryM99** [comment]
> and how do I exactly do that on the json file?

Each entry in the configuration file has 4 lines, including the curly braces before and after. Right now your network icon is to the right of the sound icon, so determine which entry matches the network icon, and cut it from that location and paste it before the entry for the sound icon.  The only tricky part is identifying which GUID number matches which icon, but with a little experimentation it's not hard.  That's why I suggested keeping a backup of the original file in case it takes a few tries to get it right. It's not drag-and-drop easy like with the Windows taskbar, but it works. As for your earlier reference to using a "custom network tray icon," I have no experience with customizing tray icons. I've always muddled along with the standard ones :)

**Comment by Nuriell** [comment]
A fast way to order try icons is to go in the RetroBar Property Settings for the icons and select "Hide when inactive" then "Always show" for all the icons you want to make always visible in order from the leftmost to the rightmost one.

**Comment by Mustardnote3943** [comment]
> A fast way to order try icons is to go in the RetroBar Property Settings for the icons and select "Hide when inactive" then "Always show" for all the icons you want to make always visible in order from the leftmost to the rightmost one.

yeah but it's not permanent. also, I'm now on linux so no more retrobar for me.
