### ISSUE TITLE
Windows Defender identifying RetroBar as Trojan:Win32/Bearfoos.B!ml

### ISSUE THREAD

**Issue by manaphychu** [dremin/RetroBar#950]
Windows just falsely detected Retrobar as a Trojan 😭

IS THIS A FALSE POSITIVE?!

**Comment by 0x5066** [comment]
yes it is

**Comment by xoascf** [comment]
Please make sure you download RetroBar from the original source: https://github.com/dremin/RetroBar/releases
Also, the antivirus you used detected it with "ml", which means it used machine learning and was not the result of proper analysis. I don't use AI for it, so maybe that's why it didn't show up for me.
